flowchart LR
    subgraph A[0 - Sopravvivenza]
    direction TB
    stepA1[Start]
    -->
    stepA2("`L'obiettivo è creare un **cashflow positivo**, quindi avere ingressi mensili superiori alle spese`")
    -->
    stepA3("`**Inizia a tracciare le spese** #13;#13;E' importante sapere dove stanno andando i soldi che escono`")
    -->
    stepA4("`Cerca di iniziare a capire se le spese sono ottimizzabili (o se puoi aumentare le entrate)`")
    -->
    |Opzionale| optA5("`Crea un piccolo fondo con 1 mese di spese`") --> stepA6
    stepA4-->stepA6
    stepA6("`Quando arrivi qui vuol dire che riesci a sopravvivere e puoi pensare agli step successivi`")
    end

    subgraph B[1 - Tutela finanziaria]
    direction TB
    stepB1("`Accumula i risparmi fino ad avere un **Fondo di emergenza** di 3-6 mesi di spese se sei un lavoratore dipendente con contratto stabile, o fino a 12 se sei un libero professionista, in modo da essere tranquillo negli imprevisti`")
    -->
    stepB2("`Valuta la sottoscrizione di un'assicurazione per proteggere la tua casa, se quella in cui vivi è di tua proprietà, e un'assicurazione sulla vita se il tuo nucleo familiare dipende dal tuo reddito`")
    -->
    stepB3("`Valuta di rimborsare tutti i debiti ad alto tasso di interesse, cioè con tasso di interesse maggiore di €STR, che hai contratto. Inizia da quelli a tasso di interesse più alto, prosegui finché non ne hai più.`")
    -->
    stepB4("`Se il tuo contratto lavorativo lo prevede, aderisci al fondo pensione negoziale versando il minimo per ottenere il contributo del datore di lavoro`")
    -->
    |Opzionale| optB5("`Se hai una RAL >50k€ valuta di effettuare ulteriori versamenti al fondo pensione fino a raggiungere il massimo deducibile di 5.164,57€  `")
    -->
    stepB6("`Quando arrivi qui vuol dire che sei al sicuro da imprevisti a breve, medio e lungo termine e puoi pensare agli investimenti`")
    stepB4-->stepB6
    end

    subgraph C[2- Investimenti a breve termine/liquidi]
    direction TB
    stepC1("`Questi investimenti sono utili quando hai bisogno di utilizzare il capitale nel giro di pochi mesi/1 anno, e non è quindi consigliabile investire in strumenti che hanno un orizzonte temporale lungo`")
    -->
    stepC2("`Nel caso in cui tu NON abbia ancora una data certa in cui ti sarà necessario utilizzare il capitale, considera un conto deposito vincolato, ma che sia **svincolabile** in qualunque momento e senza penali. Oppure un ETF monetario`")
    -->
    stepC3("`Nel caso in cui tu conosca già la data in cui avrai bisogno di usare il capitale, considera una scala di Buoni Ordinari del Tesoro - i BOT - in base alle scadenze ed agli importi previsti`")
    end

    subgraph D[3 - Investimenti a medio termine]
    direction TB
    stepD1("`Quando hai un orizzonte temporale di 2/5 anni per una spesa puoi valutare strumenti a basso rischio con scadenza che cada nel tua orizzonte temporale`")
    -->
    stepD2("`In base alla tua propensione al rischio, valuta conti deposito vincolati e/o titoli di stato della durata idonea`")
    end

    subgraph E[4 - Investimenti a lungo termine]
    direction TB
    stepE1("`Quando arrivi a questo punto e hai ancora capitale da investire, puoi valutare strumenti più a lungo termine.`")
    -->
    stepEd("`In un'orizzonte temporale > 10 anni, in base alla tua propensione al rischio, puoi scegliere di investire in ETF azionari ed in ulteriori obbligazioni a scadenza più lunga`")
    end    

    A-->B
    B-->C
    C-->D
    D-->E